/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommunicationResponseDto { 
    /**
     * Communication id
     */
    communicationId: string;
    /**
     * Communication type.
     */
    communicationType: CommunicationResponseDto.CommunicationTypeEnum;
}
export namespace CommunicationResponseDto {
    export type CommunicationTypeEnum = 'moveOutConfirmation' | 'reservationConfirmation' | 'delinquencyLate' | 'delinquencyOverlocked' | 'delinquencyLien' | 'delinquencyAuction';
    export const CommunicationTypeEnum = {
        MoveOutConfirmation: 'moveOutConfirmation' as CommunicationTypeEnum,
        ReservationConfirmation: 'reservationConfirmation' as CommunicationTypeEnum,
        DelinquencyLate: 'delinquencyLate' as CommunicationTypeEnum,
        DelinquencyOverlocked: 'delinquencyOverlocked' as CommunicationTypeEnum,
        DelinquencyLien: 'delinquencyLien' as CommunicationTypeEnum,
        DelinquencyAuction: 'delinquencyAuction' as CommunicationTypeEnum
    };
}


