/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCommunicationRequest { 
    /**
     * Communication method.
     */
    communicationMethod: CreateCommunicationRequest.CommunicationMethodEnum;
    /**
     * Communication type.
     */
    communicationType: CreateCommunicationRequest.CommunicationTypeEnum;
    /**
     * Metadata.
     */
    metaData: object;
    /**
     * Created by
     */
    createdBy: string;
    /**
     * Workflow id
     */
    workflowId?: string;
    /**
     * The email/number to send the communication to.
     */
    recipient?: string;
    /**
     * Role.
     */
    recipientRole?: string;
}
export namespace CreateCommunicationRequest {
    export type CommunicationMethodEnum = 'email' | 'sms';
    export const CommunicationMethodEnum = {
        Email: 'email' as CommunicationMethodEnum,
        Sms: 'sms' as CommunicationMethodEnum
    };
    export type CommunicationTypeEnum = 'moveOutConfirmation' | 'reservationConfirmation';
    export const CommunicationTypeEnum = {
        MoveOutConfirmation: 'moveOutConfirmation' as CommunicationTypeEnum,
        ReservationConfirmation: 'reservationConfirmation' as CommunicationTypeEnum
    };
}


