/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunicationResponseDto } from './communicationResponseDto';


export interface CreateCommunication201Response { 
    data?: Array<CommunicationResponseDto>;
    success?: boolean;
    error?: object;
}

